//
// Created by William Bernard on 4/3/19.
//

#ifndef GET_SIGNAL_STRENGTH_SIGNAL_STRENGTH_CONFIG_H
#define GET_SIGNAL_STRENGTH_SIGNAL_STRENGTH_CONFIG_H

#define GET_SIGNAL_S

#endif //GET_SIGNAL_STRENGTH_SIGNAL_STRENGTH_CONFIG_H
